//! Emits zdraw_abi.h: the single source of ABI size truth for metal_api.m's
//! _Static_asserts. Zig's @sizeOf is the only literal; the Objective-C
//! asserts consume these macros, so the two hand-maintained literal sets
//! (the drift class that fired on 2026-08-06: AttnParams widened Zig-side
//! while the C struct kept the old size) cannot diverge again. Regenerated
//! by the build on every compile of the Metal bridge.

const std = @import("std");

const mblock_c = @import("metal/mblock_c.zig");
const mblock_chain_c = @import("metal/mblock_chain_c.zig");
const metal_c = @import("metal/metal_c.zig");
const mfinal = @import("metal/mfinal.zig");
const mstack_final_c = @import("metal/mstack_final_c.zig");
const mvres_buf = @import("metal/mvres_buf.zig");
const mvres_param = @import("metal/mvres_param.zig");
const mvres_stream = @import("metal/mvres_stream.zig");
const mvres_stream_chain = @import("metal/mvres_stream_chain.zig");

const header = blk: {
    const rows = .{
        .{ "GEMM_PARAMS", metal_c.GemmParams },
        .{ "ATTN_PARAMS", metal_c.AttnParams },
        .{ "QK_NORM_PARAMS", metal_c.QkNormParams },
        .{ "LINEAR_PARAMS", metal_c.LinearParams },
        .{ "CONV_PARAMS", metal_c.ConvParams },
        .{ "BLOCK_PARAMS", mblock_c.Params },
        .{ "FINAL_NORM_PARAMS", mfinal.NormParams },
        .{ "BIAS_PARAMS", mfinal.BiasParams },
        .{ "VAE_NORM_PARAMS", mvres_param.NormParams },
        .{ "VAE_RES_PARAMS", mvres_param.ResParams },
        .{ "VAE_RES_BUFFERS", mvres_buf.ResBuffers },
        .{ "NORM_WINDOW_PARAMS", mvres_stream.NormWindowParams },
        .{ "CONV_WINDOW_PARAMS", mvres_stream.ConvWindowParams },
        .{ "ADD_WINDOW_PARAMS", mvres_stream.AddWindowParams },
        .{ "CONV_UPSAMPLE_WINDOW_PARAMS", mvres_stream_chain.ConvUpsampleWindowParams },
        .{ "STREAM_BUFFERS", mvres_stream_chain.StreamBuffers },
        .{ "CHAIN_BUFFERS", mblock_chain_c.Buffers },
        .{ "CHAIN_WEIGHTS", mblock_chain_c.Weights },
        .{ "CHAIN_PARAMS", mblock_chain_c.Params },
        .{ "CHAIN_THREADS", mblock_chain_c.Threads },
        .{ "FINAL_BUFFERS", mstack_final_c.FinalBufs },
    };
    var text: []const u8 =
        "// GENERATED by src/abi_gen.zig (zig build): do not edit.\n" ++
        "// One literal source for every Zig/ObjC struct size assert.\n" ++
        "#pragma once\n\n";
    for (rows) |row| {
        text = text ++ std.fmt.comptimePrint(
            "#define ZDRAW_ABI_{s}_SIZE {d}\n",
            .{ row[0], @sizeOf(row[1]) },
        );
    }
    break :blk text;
};

pub fn main(init: std.process.Init) !void {
    var iter = try std.process.Args.Iterator.initAllocator(init.minimal.args, init.gpa);
    defer iter.deinit();
    _ = iter.next();
    const path = iter.next() orelse return error.MissingPath;
    const z = try init.gpa.dupeZ(u8, path);
    defer init.gpa.free(z);
    const file = std.c.fopen(z.ptr, "w") orelse return error.AccessDenied;
    defer _ = std.c.fclose(file);
    if (std.c.fwrite(header.ptr, 1, header.len, file) != header.len) {
        return error.WriteFailed;
    }
}
